import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import ExternalLink from '@/components/ExternalLink';
import profilePic from '@/public/images/profile.png';

const inter = Inter({ subsets: ['latin'] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Aynur Samur</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className="mx-auto max-w-2xl w-full p-6">
          <div className="flex flex-col items-center">
            <Image
              src={profilePic}
              alt="Picture of the Aynur Samur"
              className="rounded-full w-32 h-32"
            />
            <h1 className="text-3xl mt-3 font-bold">Aynur Samur</h1>
          </div>

          <div className="mt-6">
            <p className="text-lg  mb-6">
              I am a <strong>software engineer</strong> based in Izmir. I am working on playable ads
              using <strong>JavaScript</strong> and <strong>Phaser</strong>. At the same time, I am
              making endless web game using Phaser.
            </p>

            <p className="text-lg mb-6">
              Also, I developed web project my previous company using <strong>TypeScript</strong>{' '}
              and <strong>Vue.js</strong>.
            </p>

            <p className="text-lg mb-6">
              In addition to that, I developed some <strong>React.js</strong> projects before.
            </p>

            <p className="text-lg mb-6">
              Download my{' '}
              <ExternalLink href="https://aynursamur.com/resume/AYNUR_SAMUR_Resume.pdf">
                Resume
              </ExternalLink>
              .
            </p>

            <p className="text-lg mt-6">
              Best way to contact me{' '}
              <ExternalLink href="mailto:aaynursamur@gmail.com">Email</ExternalLink>,{' '}
              <ExternalLink href="https://github.com/aynursamur">GitHub</ExternalLink>,{' '}
              <ExternalLink href="https://www.linkedin.com/in/aynursamur/">LinkedIn</ExternalLink>.
            </p>
          </div>
        </div>
      </main>
    </>
  );
}
